### ISSUE TITLE
Add ALT + Title to all pictures in documentation

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/docs#273]
- Each picture in the documentation should have valid title and good alt descriptions. 
- Add description how to use title/alt and in which format to https://merginmaps.com/docs/misc/write-docs/

Best to ask @janpaulovic1 for details

**Comment by alex-cit** [comment]
@PatrikMizera when doing this, please start with the pages that **do not have this warning** about out-of-date content. Pics that are used in this content will be changed (due to the workspace update) so I will add the titles and alt titles when fixing #271 .

![image](https://user-images.githubusercontent.com/94905350/220703568-b85992d0-f8c8-451c-83df-bfeeb6c3c380.png)
